version: 2

models:
  - name: mart_customer_revenue
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: mart_payments_incremental
    columns:
      - name: payment_id
        data_tests:
          - unique
          - not_null
      - name: customer_id
        data_tests:
          - not_null
      - name: amount
        data_tests:
          - not_null
      - name: payment_date
        data_tests:
          - not_null